version: '3.8'

services:
  project-engine-db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.0-alpine
    container_name: project-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass your_strong_password
    restart: unless-stopped

volumes:
  pgdata:
  redis_data: