spring.application.name=online_store
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=ecommerce
spring.datasource.username=postgres
spring.datasource.password=12345
#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=ecommerce
#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ??????? ??????????? ??? c??????
logging.level.com.sungurovpavel.online_store.service=DEBUG
# ?????? ?????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
