spring.application.name=online_store
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=ecommerce
spring.datasource.username=postgres
spring.datasource.password=12345
#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=ecommerce
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
